edition = "2021"
reorder_imports = true
merge_imports = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments=true
overflow_delimited_expr = true
newline_style = "Unix"
reorder_impl_items = true
blank_lines_upper_bound = 2
comment_width = 110
max_width = 110
inline_attribute_width = 80
hard_tabs = true
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 60
struct_lit_width = 24
format_strings = false
fn_single_line = false
tab_spaces = 4
